### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by bautrukevich** [bem-contrib/bem-grid#119]
Hello. I am using code from branch master, install dependencies, run ENB (./node_modules/.bin/enb make) and get the error:

```
12:57:19.792 - build failed
Error: CssSyntaxError: Number, odd or even is expected
Error result in /Users/z/Code/fiat-m.local/bower_components/bem-grid/dist/bem-grid.min.css.borschik-error
    at /Users/z/Code/fiat-m.local/bower_components/bem-grid/node_modules/borschik/lib/tech.js:86:31
    at Array.<anonymous> (/Users/z/Code/fiat-m.local/bower_components/bem-grid/node_modules/vow/lib/vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (/Users/z/Code/fiat-m.local/bower_components/bem-grid/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Error, because it's generate float number for :nth-child pseudo selector (for example: .row__col_sw_5:nth-child(2.4n), .row__col_sw_7:nth-child(1.71429n) )

How to fix? I'm running run ENB with default settings in ./enb/make.js

**Comment by awinogradov** [comment]
@bautrukevich do you want custom dist?

**Comment by bautrukevich** [comment]
@awinogradov yes, I want to set gutter 24px, as example. But "make" doesn't work even with default options.

**Comment by awinogradov** [comment]
@bautrukevich can you try https://github.com/bem-contrib/bem-grid/pull/120 and report to me?) If it is ok for you and work fine I will release new version.
